hw1 done
Fics3/Tink_Java_Backend_Course_Spring pull request #1
Opened 2024-02-11 18:22 UTC by Fics3

не знаю на счет того, как реализовал команды, хочется сделать через цепочку обязанностей, однако мне не нравится, как это будет работать с командой /help, но и мой метод как будто слишком топорный

2024-02-13 16:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +
question: эту строчку Idea code style checker добавил?

2024-02-13 16:30 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/CommandConfiguration.java
> +    CommandManager commandManager() {
можно поставить аннотацию `@Component` прям над классом `CommandManager `. В конфигурацию обычно выносят классы, над которым нед контроля (библиотечные классы); либо для которых нужно несколько инстансов (commandManager1, commandManager2 с разными настройками)

2024-02-13 16:31 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +
до конца не могу понять о какой строчке идёт речь, так как с телефона смотрю, но точно помню, что в файле с мейном ничего не менял, так что скорее всего идея добавила, пользуюсь местным форматтером кода

2024-02-13 16:32 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/TelegramBotConfig.java
> +    public TelegramBot telegramBot(ApplicationConfig applicationConfig, CommandManager commandManager) {
Вот как раз и пример)
TelegramBot - внешний класс, над ним не можем поставить анноташку `@Component`, так что регистрируем бин в конифгурации

2024-02-13 16:33 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/TelegramBotConfig.java
> +public class TelegramBotConfig {
Небольшая ремарка: лучше называть в едином стиле, т.е. либо все классы-конфигурации оканчиваются на `Config`, либо все класс-конфигурации оканичваются на`Configuration`. Я предпочитаю суффикс Configuration, но это где как)

2024-02-13 16:56 UTC, iskanred commented on bot/src/main/java/edu/java/bot/model/commands/CommandManager.java
> +        commandMap.put("/help", new HelpCommand());
issue: у тебя сейчас не совсем удобно добавлять новые команды.
Нужно будет написать имя команды в двух местах - тут и еще в самой команде в `getName()`.
+ `CommandManager` - это не менеджер, а просто обертка над Map.
Подумай по поводу архитектуры, как по-другому сделать можно, чтобы добавлять команду или хотя бы ее имя требовалось только в одном месте.

2024-02-13 17:00 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/NotificationService.java
> +@Getter @Service
chore: анноташки лучше ставить друг на друга, чем сбоку

2024-02-13 17:02 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/service/NotificationService.java
> +@Getter @Service
это тоже идеевские приколы, не знаю, как убрать перенос аннотаций

2024-02-13 17:04 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/model/commands/CommandManager.java
> +        commandMap.put("/help", new HelpCommand());
ой, совсем не подумал об этом
Только немного не могу понять, как вызывать этот бин, по имени?

2024-02-13 17:13 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/TelegramBotConfig.java
> +    private SetMyCommands setMyCommands(CommandManager commandManager) {
Посмотри сначала нижний комментарий по поводу класса `CommandManager`.
Я бы переработал решение и сделал хорошее MVC со следующими слоями Controller -> Service -> Repository.

Но вам пока этого не объясняли вроде, поэтому если идти от текущей архитектуры можно сделать так:
создать `@Bean` который будет отдавать саму мапу команд, а не менеджер. Чтобы два раза команды вручную не вводить (т.к. есть риск ошибиться в одном из мест), можно сделать как-то так:

псевдокод:
```java
commandsArray = [new Command1(), new Command2(), ...]
Map<String, Command> commands = commands.arrayToMap(c -> 
    c.getName(), c
)
```

2024-02-13 17:15 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/TelegramBotConfig.java
> +            .map(command -> new BotCommand(command.getName(), command.getDescription())
если использовать функциональный стиль, то нужно бить вызов каждый функции по строчкам:
```java
commandManager
    . getCommandMap()
    .values()
    .stream()
    .map(command -> new BotCommand(command.getName(), command.getDescription()))
    .toArray(BotCommand[]::new));
```
так понятнее)

2024-02-13 17:27 UTC, iskanred commented on bot/src/main/java/edu/java/bot/model/commands/ListCommand.java
> +    public String execute(long chatId, String message, NotificationService updateListener) {
issue: идея передавать Service-класс в класс модели - сомнительная, попробуй почитать как строится Sring MVC, что такое Model, View, Controller, Service.
Обычно классы-модели не несут в себе никакой логики, к счастью или к сожалению. Тоже тема спорная, но в индустрии и на спринге пишут модели просто классы, которые хранят в себе данные, например паттерн DTO (Data-Transfer-Object). А исполняет всю бизнес-логику классы-сервисы как раз.

2024-02-13 17:29 UTC, iskanred commented on bot/src/main/java/edu/java/bot/model/commands/StartCommand.java
> +        return "registration";
все строки можно вынести в static переменные в этом же классе (name, description, "Hello, World"). В других классах тоже самое

2024-02-13 17:44 UTC, iskanred commented on bot/src/main/java/edu/java/bot/model/User.java
> +        links = new ArrayList<>();
style: лучше тоже this поставить

2024-02-13 17:47 UTC, iskanred commented on bot/src/main/java/edu/java/bot/model/commands/CommandManager.java
> +        commandMap.put("/help", new HelpCommand());
> ой, совсем не подумал об этом Только немного не могу понять, как вызывать этот бин, по имени?

да, добавляешь в класс с помощью `@Autowired`, если нужно и он нужный тип сам подставит

2024-02-13 18:16 UTC, iskanred commented
В целом здорово постарался, красавчик! Пока ставлю 7/8 за архитуктурный подход, потому что это влияет на дальнейшее расширение и масштабирование. В общем если сможешь архитектуру поправить в соответствии с MVC паттерном, дальнейшие домашки будет просто решать)

Комментарии по code style или всякие анноташки - просто предложения и заметки, они на оценку не влияют. Как все поправишь - присылай, думаю 8/8 будет)

2024-02-14 19:19 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/model/commands/ListCommand.java
> +    public String execute(long chatId, String message, NotificationService updateListener) {
я уже писал проекты с MVC, но это было веб приложение и подобные команды можно было маппить в контроллере, однако в этом проекте я не представляю, как выстроить архитектуру именно с командами.
с конфигурациями я разобрался, но не могу придумать решение кроме как перенести все классы, связанные с командами, в сервис, но очень смущает, что в сервисах у меня лежат классы, которые не помечены сервисом и, хоть являются важными
Разделять же данные и логику работы смысла я не вижу, как будто это излишне

2024-02-15 19:25 UTC, iskanred approved these changes
Отлично!

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/NotificationService.java
> +@Getter @Service
покопай в сторону исправления `.editorconfig` или применения его настроек по локальному файлу, мб в этом дело:
https://www.jetbrains.com/help/idea/editorconfig.html

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/model/commands/resourcesHandlers/ChainResourceHandler.java
> +public abstract class ChainResourceHandler {
note: Круто реализовал паттерн цепочки обязанностей 💪

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/model/commands/resourcesHandlers/GitHubHandler.java
> +        return "github.com";
такие строчки тоже можно хранить в ApplicationConfig, чтобы в одном файле смотреть все переменные, а не бегать по коду и искать

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/NotificationService.java
> +        } catch (NullPointerException e) {
в java мире nullpointer может выскочить в абсолютно разных ситуациях и не только по вине нашего кода, но и библиотеченого.

Здесь три строки обернуты в try-catch и не очень понятно, откуда же именно он может свалиться (а свалиться может откуда угодно, как показывает практика)).

+ вообще не рекомендую основывать кейсы бизнес-логики на выбросах исключений, особенно на nullpointer! Лучше вручную if-ом проверить, что из `.get(parsedMessage[0])` вернется null и в таком случае вернуть соответствующее сообщение.

А вообще лучше создать свои исключения типа `UserInterfaceException` (родительский класс) и в конце в самом контроллере просто выводить -` try { ... } catch(UserInterfaceException e) { showMsgToUser(e.getMessage()) }`

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/resources/application.yaml
> +    telegram-token: ${TELEGRAM_API_KEY}
✅

2024-02-15 19:25 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/HelpCommandTest.java
> +        // Act
круто, что разбил на три части и комменты оставил 💪

2024-02-15 19:25 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/HelpCommandTest.java
> +    void testGetName() {
немножко избыточный тест, ты просто проверяешь тут, что имя поля в классе действительно `/help`, хотя такие простые вещи обычно не проверяют

можно это не тестить везде, где такое есть

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/NotificationUpdateListener.java
> +    public int process(List<Update> updates) {
обыччно в контроллере никакой логики нет, он просто делегирует запросу сервис-классу, который в свою очередь может делегировать запрос в другие-сервис классы, и возвращает ответ от этого класса + может обработать ошибки

2024-02-15 19:25 UTC, iskanred commented on bot/src/test/java/edu/java/bot/service/NotificationServiceTest.java
> +    public void testGetCommand_ValidCommand_ReturnsExpectedResult() {
style: лучше использовать либо нижние подчеркивания либо camel case, тоже на твое усмотрение, просто в реальных проектах не встречал такого именования тестов прикольного)

2024-02-15 19:25 UTC, iskanred commented on scrapper/pom.xml
> +            <exclusions>
question: а подскажи, почему решил исключить? idea подсказала? или мешалось запуску? мб уязвимость какая-то была

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +
там пустая строка, я оставил тебе на покопать в сторону применения и/или изменения настроек .editorconfig + после этого можешь форматтер еще раз запустить:
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/model/commands/ListCommand.java
> +    public String execute(long chatId, String message, NotificationService updateListener) {
В целом ты прав, оставь пока так. Если что изменишь в будущих домашках

2024-02-15 19:25 UTC, iskanred commented on scrapper/pom.xml
> +            <exclusions>
ответь, пж, интересно)

2024-02-15 19:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/TelegramBotConfig.java
> +                .toArray(BotCommand[]::new));
style:
```java
        return new SetMyCommands(
            commandMap
                .values()
                .stream()
                .map(command -> new BotCommand(command.getName(), command.getDescription()))
                .toArray(BotCommand[]::new)
        );
```

2024-02-16 14:15 UTC, Fics3 commented on scrapper/pom.xml
> +            <exclusions>
а это не я делал, в чате выкладывали, что надо помники поменять из-за какой-то ошибки, поэтому тут я сам не знаю

2024-02-16 14:31 UTC, Fics3 commented on bot/src/test/java/edu/java/bot/service/NotificationServiceTest.java
> +    public void testGetCommand_ValidCommand_ReturnsExpectedResult() {
вообще camel и использую, но иногда не получается сделать ёмкое название с его помощью. мне один из предыдущих проверяющих посоветовал такой паттерн наименования, вообще удобно, особенно, когда тестов много, а каждый называть testMethodSomething уже не хватает фантазии да и смысл теста из названия не получается понять

2024-02-18 17:14 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/controller/NotificationUpdateListener.java
> +    public int process(List<Update> updates) {
вынес всю логику кроме проверки на null( технически и ее вынес) и цикла, все update полностью обрабатываются в сервисе

2024-02-19 19:01 UTC, iskanred requested changes
Оставил комменты и запрос на внесение изменений по итогам ревью

2024-02-19 19:01 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/NotificationUpdateListener.java
> +            if (notificationService.messageIsNull(update)) {
не, ну до такого можно не доводить)
почему notificationService отвечает за какие-то проверки сообщений на null?)

кажется, что за такое должен отвечать какой-то валидатор или чекер

Оставь проверку на null, ты же просто входные данные проверяешь. Если бы ты какие-то сложные проверки реализовывал, можно было вынести это в класс `*Validator` и вызывать у него функцию `isValidMessage()`, а так обычной проверки на null хватит)

2024-02-19 19:01 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/CommandConfig.java
> +    private final static Command[] COMMANDS = {
я, кстати, подумал, как можно решить твою проблему с MVC

Команды можно сделать бинами и назвать типа `HelpCommandService` и т.п., в них будет вызов метод, который принимает в себя `update` или чето такое

В этом классе сделать список таких сервисов в конструкторе, а Spring сам заинжектит в этот список все бины (подробнее [тут](https://www.baeldung.com/spring-injecting-collections#reference), 5й раздел)

p.s. лучше хранить список, чем массив, с ним удобнее и безопаснее работать

2024-02-21 19:15 UTC, iskanred requested changes
.

2024-02-21 19:15 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/CommandConfig.java
> +    Map<String, Command> commandMap() {
по поводу моего прошлого ревью: тогда, скорее всего, придется либо менять Map на HashMap (или любую другую реализацю), либо обратно возвращать класс-обертку), либо приписать `@Qualifier`

Дело в том, что, если мапа содержит классы, которые явлются спринговыми бинами, то спринг автоматом положит в ключ имя бина

можно почитать тут подробно: https://habr.com/ru/companies/otus/articles/487750/

2024-02-22 10:53 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/configuration/CommandConfig.java
> +    Map<String, Command> commandMap() {
На самом деле оказалось очень простое решение, если задуматься, но я все еще не до конца понимаю, что именно можно называть сервисом.

Я думал, что загонять слишком много классов в контекст спринга наверное тоже не очень хорошо, изначально была эта идея: cделать команды сервисами/компонентами, но мне показалось, что это несовсем хорошая практика( не знаю почему, нигде не нашел внятного ответа на свой вопрос)

Есть вообще какое-то соглашение по этому поводу или тут все очевидно и я просто не могу этого понять?

Еще в паре мест использовал Autowired, тут нам семинарист рассказывал, что нелучшая практика его использовать, но в этом случае оно мне помогло подтянуть все команды, не прибегая к добавлению команд туда, создал команду, пометил сервисом и все работает

2024-02-22 16:46 UTC, iskanred requested changes
Запросил изменения.

По поводу сервисов:
Сервисом можно называть все, что должно исполнять бизнес-логику. Т.е. контроллер отвечает за запросы/ответы, репозиторий за работу с хранилищем, модель просто несет данные, а всю "основную" работу делает именно сервис.

Т.е. проверка каких-то правил, запросы в другие сервисы - за все отвечает сервисный слой. При этом он никогда не может быть в начале или конце запроса, он всегда по середине.

Т.е.
1. контроллер в начале
2. репозиторий или клиент какого-то другого API - в конце
3. а сервисы всегда в центре этого взаимодействия

Например,
Контроллер обработал запрос на проверку клиента - нужно посчитать его рейтинг исходя из каких-то параметров:
1. Контроллер отдает ID клиента сервису `ClientRartingService`
2. `ClientRartingService` сервис говорит `ClientRepository`: вытащи мне такие-то параметры по ID клиента
3. Далее `ClientRartingService` отдает запрос в `SourceSelectorService`, который как-то принимает решение в какие источники сделать запрос, исходя из полученных параметров
4. Далее `ClientRartingService` отдает запрос какждому из `Source1Service`, `Source2Service`, `SourceNService`, которые мы получили от `SourceSelectorService`. Каждый такой сервис обращается в какой-то источник данных. В самом конце `ClientRartingService` отдает ответы от разных источников в `CalculatorService`, где по какой-то сложной формуле считается итоговый рейтинг
5. `ClientRartingService` возвращает этот рейтинг

Это в целом вполне реальный кейс и сильно упрощенный

2024-02-22 16:46 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/CommandConfig.java
> +    private List<CommandService> commandServices;
можно попробовать этот лист передать прям в параметры метода `commandMap()` и посмотреть, подтянет ли спринг этот лист

должно сработать и без `@Autowired`

2024-02-22 16:46 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/NotificationService.java
> +    public NotificationService() {
почем убрал инициализацию из конструктора в приватное поле? так хуже для тестирования (мокать тяжелее)

попробоуй
```java
public NotificationService(@Autowired @Qulifier("commandMap") Map<String, CommandService> commandMap) {
```

2024-02-26 13:53 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/service/NotificationService.java
> +    public NotificationService() {
точно такую инициализацию не вставил, @Autowired так не работает, поэтому мапу все таки вкинул через конструктор и в целом убрал @Autowired, оставив мапу приватным полем

2024-02-26 23:11 UTC, iskanred approved these changes
✅

2024-02-27 09:15 UTC, merged