hw2 done
Fics3/Tink_Java_Backend_Course_Spring pull request #2
Opened 2024-02-21 17:16 UTC by Fics3

не знаю на счет того, какая здесь должна быть структура, конфиги понятно, все остальное, как есть. Распределил, как было удобно работать

2024-02-25 17:57 UTC, iskanred requested changes
Вроде все ок, нужно только правки внести) + Не увидел файла application.yaml для Scrapper, в котором бы лежало значение для `@Scheduled`.

Лучше пакетирование сделать по типу класса:
* `src/main/.../client/GitHubClient`
* `src/main/.../client/StackOverflowClient`
* `src/main/.../dto/StackOverflowQuestionResponse`
и так далее

2024-02-25 17:57 UTC, iskanred commented on scrapper/pom.xml
> +<!--        </dependency>-->
можно удалять?

2024-02-25 17:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    @Bean WebClient getStackoverflow() {
чего-то тут опять анноташка съехала

2024-02-25 17:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    @Bean WebClient getStackoverflow() {
лучше назвать метод просто `stackoverflowClient`. В нейминге биновых методов не используют глаголы

2024-02-25 17:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public WebClient getGitHubClient() {
лучше назвать метод просто `githubClient()`. В нейминге биновых методов не используют глаголы

2024-02-25 17:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/github/GitHubClient.java
> +public class GitHubClient {
Почему бы не сделать класс компонентом `@Component`?)
Тогда нужный вебклиент можно подтягуть автоматически спрингом по имени бина

А тестировать можно через `@MockBean`

2024-02-25 17:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/github/GitHubClient.java
> +        String apiUrl = String.format("/repos/%s/%s", owner, repo);
эту строчку `"/repos/..."` можно тоже вынести в константное поле по аналогии со stackoverflow

2024-02-25 17:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/util/DurationConverter.java
> +    public static long convertToMillis(String durationString) {
вообще спринг сам может парсить строки в `Duration`

Для `@Scheduled` варианта можно сделать, например, вот так:
https://stackoverflow.com/questions/59786883/is-there-way-to-use-scheduled-together-with-duration-string-like-15s-and-5m

2024-02-28 21:17 UTC, Fics3 commented on scrapper/src/main/java/edu/java/util/DurationConverter.java
> +    public static long convertToMillis(String durationString) {
спасибо большое!! вообще не подозревал, что спринг и такое может, так еще и несколькими способами
Решил взять способ с конфигом, а не PT10S, выглядит, как более гибкое + понятное решение

2024-02-29 21:47 UTC, iskanred commented
Не забудь ревью запросить, как закончишь с правками, я гляну и аппрувну PR

2024-02-29 21:53 UTC, Fics3 commented
а я ещё вчера все закончил
мне в прошлом семестре не очень удалось поработать с гитом и проверяющими, не знал, что ревью можно запрашивать, дальше оперативнее буду работать!!

2024-02-29 22:55 UTC, iskanred requested changes
Круто! Остались минорные правки

2024-02-29 22:55 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public WebClient getGitHubClient() {
question: почему решил не менять имя метод, а ставить qualifier?)

2024-02-29 22:55 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public WebClient getStackoverflow() {
а тут почему-то вообще без client)

2024-02-29 22:55 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/LinkUpdaterSchedulerConfig.java
> +public class LinkUpdaterSchedulerConfig {
не думал в использование `record` из java 17 вместо классов? тогда бы и getter setter не пришлось генерить

2024-02-29 22:55 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/GithubClient.java
> +    }
question: в курсе, что можно использовать `@AllArgsConstructor` или `@RequiredArgsConstructor`? В данном кейсе не особо применимо, т.к7 нужен `Qualifier`, но вообще в курсе?

2024-02-29 22:57 UTC, iskanred commented
Если будут какие-то интересные/важные вопросы, либо буду подолгу не отвечать/ревьюить, можешь писать в телегу мне)

2024-03-01 16:21 UTC, Fics3 commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public WebClient getStackoverflow() {
с именами методов какая-то непонятка произошла, вроде все менял, в данный момент исправил.
А Qualifier стоит, потому что без него банально не работает.
Вот такая ошибка вылетает:
`The bean 'githubClient', defined in class path resource [edu/java/configuration/ClientConfig.class], could not be registered. A bean with that name has already been defined in file [/home/digital-nishtyak/IdeaProjects/java-course-2023-backend-template/scrapper/target/classes/edu/java/client/GithubClient.class] and overriding is disabled.`
Сколько бы формувов не перерыл, но не могу догнать, почему бины конфликтуют, хотя Qualifier вроде как так же работает

2024-03-01 17:19 UTC, Fics3 commented on scrapper/src/main/java/edu/java/configuration/LinkUpdaterSchedulerConfig.java
> +public class LinkUpdaterSchedulerConfig {
вообще думал, но именно тут оно как будто не нужно, слишком неудобная инфрастуктура становится, да и interval не получается пропихнуть в record, как бы не пытался, а если его убирал, то получался код, где я просто передаю Duration interval в функцию, которая и должна возвращать интервал, а это вообще будто неправильный подход, поэтому решил остаться на классе, но с аннтошками
Я возможно пока не понял, как именно надо пропихивать в record конфигурации переменнные, потому что пока что выглядит очень запутанно

2024-03-01 17:24 UTC, Fics3 commented on scrapper/src/main/java/edu/java/client/GithubClient.java
> +    }
вообще слышал, но стараюсь меньше ломбока использовать, геттеры, сеттеры и логгеры беру оттуда, а все остальное с опаской применяю, так как очень много мне рассказывали, какой ломбок неоднозначный

2024-03-03 18:09 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/GithubClient.java
> +    }
а можешь пояснить, что имеешь в виду под неодназначностью?

2024-03-03 18:21 UTC, iskanred requested changes
Ответил на вопросы

2024-03-03 18:21 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/LinkUpdaterSchedulerConfig.java
> +public class LinkUpdaterSchedulerConfig {
понял, ну вообще можно без проблем сделать, с чем именно трудности, допустим, в такой реализации:

```java
@ConfigurationProperties("app.scheduler", ignoreUnknownFields = false)
public record Scheduler(@NotNull Duration interval) { }
```

2024-03-03 18:21 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public WebClient getStackoverflow() {
аа, ну смотри, у тебя бин с именем `gitHubClient` уже существует, ты его определил, когда поставил над классом `GitHubClient` аннотацию `@Component`. Спринг взял имя класса и просто первую букву сделал маленькой

тут ты пытаешься снова бин создать с таким же именем, а в спринге не может быть двух одинаковых бинов с одним и тем же именем, даже если у них разные типы

если назовешь здесь бин `gitHubWebClient`, то должно заработать без `@Qualifier`

2024-03-03 18:38 UTC, Fics3 commented on scrapper/src/main/java/edu/java/client/GithubClient.java
> +    }
Что некоторые аннотации ломают проекты и есть функции ломбока, которые в целом отключают.
Сам щас не вспомню, что за функции именно, но мне каждый жава разработчик дает полярное мнение на счет ломбока, кто-то без него жить не может и говорит, что удобный и вообще маст хев, а кто-то наоборот максимально ужасно отзывается, говоря, что это вред и он только хуже проекту делает. Я, в связи со всем этим, пользуюсь ломбоком, так как реально удобно бывает, но осторожно и не все анноташки возможные использую
Думаю с `@AllArgsConstructor` или `@RequiredArgsConstructor` проблем не будет, но сам факт наличия таких отзывов о библиотечке заставляет задуматься

2024-03-04 17:36 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/GithubClient.java
> +    }
Ну вообще, главное, что знаешь, а остальное на свое усмотрение используй)

2024-03-07 13:05 UTC, Fics3 commented
c qualifier все понял и поменял, но уже совершенно запутался с тем, почему у меня рекорд не работает, все одна ошибка вылетает `A component required a bean named 'app' that could not be found.` 
```@Validated
@ConfigurationProperties(prefix = "app.scheduler", ignoreUnknownFields = false)
public record SchedulerConfig(
    boolean enable,
    @NotNull Duration interval,
    @NotNull Duration forceCheckDelay
) {
}```
```@Log4j2
@Component
public class LinkUpdaterScheduler {

    @Scheduled(fixedDelayString = "#{@app.scheduler-edu.java.configuration.SchedulerConfig.interval.toMillis}")
    public void update() {
        log.info("Произошло обновление");
    }
}```

2024-03-09 00:26 UTC, iskanred commented
> c qualifier все понял и поменял, но уже совершенно запутался с тем, почему у меня рекорд не работает, все одна ошибка вылетает `A component required a bean named 'app' that could not be found.`
> 
> ```java
> @ConfigurationProperties(prefix = "app.scheduler", ignoreUnknownFields = false)
> public record SchedulerConfig(
>     boolean enable,
>     @NotNull Duration interval,
>     @NotNull Duration forceCheckDelay
> ) {
> }
> @Log4j2
> @Component
> public class LinkUpdaterScheduler {
> 
>     @Scheduled(fixedDelayString = "#{@app.scheduler-edu.java.configuration.SchedulerConfig.interval.toMillis}")
>     public void update() {
>         log.info("Произошло обновление");
>     }
> }```
> ```

Вообще я глянул, у тебя же уже используется `record Scheduler` внутри ApplicationConfig, можно же сразу его использовать и не выносить отдельно в `LinkUpdaterSchedulerConfig`.

2024-03-09 00:33 UTC, iskanred approved these changes

2024-03-09 00:33 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public WebClient stackoverflowClient() {
ну кажется нейминг немного запутанный: это же инстанс класса webClient, логично назвать `stackoverflowWebClient`, а сам класс, который использует можно назвать `StackOverflowClient` просто

2024-03-10 15:01 UTC, iskanred approved these changes
аппрувлю с одной помаркой

2024-03-10 15:01 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Bean
вроде можно убрать и оставить только `@NestedConfigurationProperty`

2024-03-10 16:02 UTC, Fics3 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Bean
неа, он перестает видеть его как `@Bean`, как я понял, `@NestedConfigurationProperty` просто позволяет заполнить внутренне поле из .yml файла, однако мы все еще не регистрируем `Scheduler`, как бин, а следовательно не можем вытащить его с помощью SPeL, который как раз и берет все из контекста спринга
Долго со всем этим делом мучался, но только `@Bean` решил мою проблему
![image](https://github.com/Fics3/Tink_Java_Backend_Course_Spring/assets/114524392/63a97dda-e9aa-4c16-adb4-562ce1c88181)

2024-03-10 22:13 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Bean
Да, ты прав
https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/context/properties/NestedConfigurationProperty.html

2024-03-10 22:14 UTC, iskanred approved these changes
Final approve

2024-03-22 10:53 UTC, merged