Hw5
Fics3/Tink_Java_Backend_Course_Spring pull request #5
Opened 2024-03-16 15:25 UTC by Fics3

2024-03-25 20:17 UTC, iskanred commented
Что-то файлов многовато. Что-то с гитом случилось?

2024-03-25 20:22 UTC, Fics3 commented
> Что-то файлов многовато. Что-то с гитом случилось?

да, пока работал над дз вылетело, что в гите поломанные файлы, пришлось восстановить и сделать часть работы с нуля, благо уже занимался таким

2024-03-25 20:48 UTC, iskanred requested changes
8/8 🔥
Круто постарался, но без правок никуда, на то и нужны ревью)

2024-03-25 20:48 UTC, iskanred commented on bot/src/main/java/edu/java/bot/client/ScrapperClient.java
> +    @Value(value = "${app.scrapper-properties.chat}")
не стал пока в проперти класс выносить отдельный?

2024-03-25 20:48 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/repository/ChatRepositoryTest.java
> +    @Rollback
если аннотация у всех методов, можно перенести на уровень класса, как правило

+вроде же она и так true по дефолту для spring test context:

`Rollback for integration tests in the Spring TestContext Framework defaults to true even if @Rollback is not explicitly declared.`
https://docs.spring.io/spring-framework/reference/testing/annotations/integration-spring/annotation-rollback.html

2024-03-25 20:48 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +    }
не думал, попиить на несколько методов, в том числое приватных? А то метод великоват

2024-03-25 20:48 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +        };
Можно вынести `checkForUpdate` в общий интерфейс `UpdateChecker`, который потом реализовать двумя сервисами `GithubUpdateChecker` и стековерфлоу.

Тогд можно мапу доменов (url -> service), которые, кстати, тоже лучше хранить в пропертях:
```yaml
resources:
    github:
       base-url:
       domain:
       repo:
    stackoverlow:
      ....
```

В общем в зависимости от домена пришедшего урла выбирать нужный `updateChecker`:
```java
domainToUpdateCheckers[url.getHost()].checkForUpdate(url);
```

Над названием переменных нужно получше подумать только)

2024-03-25 20:48 UTC, iskanred commented on scrapper/src/main/java/edu/java/util/DateUtil.java
> +public final class DateUtil {
можешь поглядеть `@UtilityClass` анноташку в ломбоке. Но она вроде эксперементальная, так что смотри сам, использовать или нет)

2024-03-25 20:54 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/client/ScrapperClient.java
> +    @Value(value = "${app.scrapper-properties.chat}")
вынес, просто уже в бонусе это сделал) не хотел в двух ветках это менять

2024-03-25 21:01 UTC, Fics3 commented on scrapper/src/test/java/edu/java/scrapper/repository/ChatRepositoryTest.java
> +    @Rollback
о, спасибо, не знал про rollback

2024-03-26 20:44 UTC, Fics3 commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkUpdater.java
> +    }
Вообще в 6 домашке так и сделал, но после твоей идеи с мапой updateChecker'ов для разных ресурсов в голове все перевернулось и теперь скорее всего так и перепишу, потому что мой вариант со свичкейсом мне хоть и больше нравился, чем ifelse, но все равно как-то неудобно добавлять новую логику и ресурсы, да и код нечитабельным становился, спасибо!!

2024-03-27 19:46 UTC, iskanred requested changes
Пушка 💯

Остались небольшие правки

2024-03-27 19:46 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +            .baseUrl(applicationConfig.githubProperties().repos())
🔥

2024-03-27 19:46 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/LinkUpdater.java
> +    private Duration threshold;
почему решил не инжектить в конструктор? тестить было бы проще

2024-03-27 19:46 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/service/jdbc/LinkServiceTest.java
> +@SpringBootTest
ты тут для теста поднимаешь весь контекст спринга => все бины, хотя используешь только один

Можно указать в этой анноташке списком все бины, которые нужны для теста

2024-03-27 21:12 UTC, Fics3 commented on scrapper/src/test/java/edu/java/scrapper/service/jdbc/LinkServiceTest.java
> +@SpringBootTest
я думал, исправлял, менял, в итоге анноташку снес

2024-03-28 08:41 UTC, iskanred approved these changes
✅

2024-03-28 17:29 UTC, merged