Hw5bonus
Fics3/Tink_Java_Backend_Course_Spring pull request #6
Opened 2024-03-17 18:39 UTC by Fics3

Не нравится структура проекта, правильно ли вообще, что у нас куча по сути одинаковых сервисов, которые работают с разными репами, или тут все чисто в целях обучения так сделано?

2024-03-25 21:12 UTC, iskanred requested changes
🔥 Все выглядит здорово, единственное, нужны правки + правки из ДЗ№5
Не хватило тестов для jooq репозиториев, поэтому пока 14/15.

В идеале хочется еще видеть, чтобы сервисы были в едичном экземпляре и тесты на них тоже! Т.е. придумать, как параметризировать тесты реализацией репозитория. Если уже сделал это в 6й домашке, тогда напиши это в запросе на ревью, я учту! Если нужна помощь, подсказки или что-то непонятно, можешь заходить в тг.

Присылай запрос на ревью с правками + можешь на портале дополнительно тоже, т.к. я домашку уберу в статус "требуются доработки".

P.S. У меня еще вопрос. Ты когда собираешься мержить PR прошлые?) А то они копятся и копятся, с такой кучей веток, наверное, работать неудобно)

2024-03-25 21:12 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/GithubClient.java
> +    }
`GitHubClient` это не тот уровень абстракции, на который стоит выносить это поведение. Клиент обычно соотвествует API сервиса (гитхаба). + Ко всему непонятно, что за метод, обновление чего он отдает и причем тут ссылка. Я бы вынес это в сервисный слой, где вызов используется)

для stackoverlow также

2024-03-25 21:12 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/ClientConfig.java
> +    public WebClient scrapperWebClient(@Value("${app.scrapper-properties.url}") String baseUrl) {
тут тоже стоит вынести в проперти-класс `ScrapperProperties`

2024-03-25 21:12 UTC, iskanred commented on bot/src/test/java/edu/java/bot/controller/TestConfig.java
>  public class TestConfig {
для таких случаев есть `@TestConfiguration`:
https://reflectoring.io/spring-boot-testconfiguration/

2024-03-25 21:12 UTC, iskanred commented on bot/src/main/java/edu/java/bot/client/ScrapperClient.java
> +    public ScrapperClient(WebClient scrapperWebClient, ApplicationConfig applicationConfig) {
ага, увидел, что тут ты уже используешь проперти, кайф!

2024-03-25 21:12 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/WebServerController.java
> +        return ResponseEntity.ok("Обноавление обработано");
все-таки можно сделать, чтобы этот метод возвращал `String` и тут написать:
```java
return "Обновление обработано";
```

2024-03-25 21:12 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/WebServerController.java
> +        log.info(linkUpdateRequest.description());
это не разные логи)
если логируешь объект, то логируй в рамках одного лога)

Если `LinkUpdateRequest` это `record`, то можно сразу `request.toString()` бахнуть, у рекордов `toString` переопределен по дефолту:
https://www.baeldung.com/java-record-keyword

Если нет, то конкатенацией

2024-03-25 21:12 UTC, iskanred commented on scrapper-jooq/pom.xml
> +        </dependency>
этот модуль - "библиотечный" и не подразумевает использование спринга. Ну ты его и не используешь)

Так что можешь зависимости на спринг удалить, они не нужны

2024-03-25 21:12 UTC, iskanred commented on scrapper/src/main/java/edu/java/client/GithubClient.java
> +        String apiUrl = String.format(applicationConfig.githubProperties().url(), urlSplit[1], urlSplit[2]);
я бы создал переменные `owner` и `repo`, чтобы было представление, форматирование чего проихсодит

со стэковер также)

2024-03-25 21:12 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/TelegramChatController.java
> +    public ResponseEntity<String> registerChat(@PathVariable Long id) {
опять же, в `ResponseEnity` оборачивать необязательно

Мб писал тебе уже об этом, и ты это уже исправлял, просто изменения пока не смержились) Но не знаю точно

2024-03-25 21:12 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/repository/jdbc/JdbcChatRepository.java
> +public class JdbcChatRepository {
лучше чтоб две реализации (jdbc и jooq) имели один и тот же интерфейс, чтобы потом удобнее было выбирать динамически нужную конифгурацию "по кнопке")

но мб в hw6 ты это уже реализовал

2024-03-25 21:12 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
вот сервисы лучше как раз не разделять на детали реализации, чтобы соблюдать принципы SOLID - а конкретно последний 'dependency inversion'. Сервис должен ничего не знать про реализации БД, он просто должен использовать интерфейс репозитория, с которым работает.

А уже какая реализация будет тянуть можно настроить с помощью `@Conditional...` аннотаций или `@Qualifier` или `@Primary`

2024-03-25 21:12 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/repository/mapper/ChatMapper.java
> +package edu.java.domain.repository.mapper;
кажется, что mapper нужен только для jdbc, поэтому должен лежать внутри пакета jdbc ко всему прочему

2024-03-26 18:52 UTC, iskanred commented
> Не нравится структура проекта, правильно ли вообще, что у нас куча по сути одинаковых сервисов, которые работают с разными репами, или тут все чисто в целях обучения так сделано?

Не в целях, но в рамках обучения да)
То, что не нравится - это правильно! Решение - не очень самом деле. Поэтому и рекомендовал сервис один оставить для каждого из юзкейсов без разделение на реализацию репозитория

2024-03-26 18:57 UTC, Fics3 commented
> > Не нравится структура проекта, правильно ли вообще, что у нас куча по сути одинаковых сервисов, которые работают с разными репами, или тут все чисто в целях обучения так сделано?
> 
> Не в целях, но в рамках обучения да)
> То, что не нравится - это правильно! Решение - не очень самом деле. Поэтому и рекомендовал сервис один оставить для каждого из юзкейсов без разделение на реализацию репозитория 

так а jpa реализуется не на общих интерфейсах, уж специфика у него такая, тогда как мне сделать общий сервис для всех реп

2024-03-26 19:14 UTC, iskanred commented
> > > Не нравится структура проекта, правильно ли вообще, что у нас куча по сути одинаковых сервисов, которые работают с разными репами, или тут все чисто в целях обучения так сделано?
> > 
> > 
> > Не в целях, но в рамках обучения да)
> > То, что не нравится - это правильно! Решение - не очень самом деле. Поэтому и рекомендовал сервис один оставить для каждого из юзкейсов без разделение на реализацию репозитория
> 
> так а jpa реализуется не на общих интерфейсах, уж специфика у него такая, тогда как мне сделать общий сервис для всех реп

Можно в репозитории Jpa, которые будут реализовывать твой интерфейс, положить бины репозиториев Jpa, которые заполнит спринг:
```java
interface MyRepository { }

interface JpaEntity...Repository extends JpaRepository<...> { }

@Repository
class JpaMyRepository implements MyRepository {
    JpaEntity...Repository jpaRepository;
    ...
}

@Repository
class JdbcMyRepository implements MyRepository {
...
}
...
```

2024-03-27 21:58 UTC, Fics3 commented on scrapper/src/main/java/edu/java/client/GithubClient.java
> +        String apiUrl = String.format(applicationConfig.githubProperties().url(), urlSplit[1], urlSplit[2]);
![image](https://github.com/Fics3/Tink_Java_Backend_Course_Spring/assets/114524392/8dff7dcf-c244-4dbf-bc4f-2fc8e6e965ef)
а у меня же как раз в стековере нормально указано, что это айди вопроса
с гитом переделал, реально непонятно, че я там вообще делаю без констекста

2024-03-27 22:01 UTC, Fics3 commented on scrapper/src/main/java/edu/java/domain/repository/jdbc/JdbcChatRepository.java
> +public class JdbcChatRepository {
Реализовал!!
сюда тоже добавил, раз делаю одну версию сервисов на всех

2024-03-27 22:05 UTC, Fics3 commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
я вот как раз поэтому и спрашивал, нормально ли это, потому что код у меня в итоге везде одинаковый, просто у нас в заданиях требовалось реализовывать для каждого отдельный сервис, очень раз зеленому свету на адекватную реализацию сервисов
![image](https://github.com/Fics3/Tink_Java_Backend_Course_Spring/assets/114524392/d000a76e-3c6c-40c9-a4d3-0539b439760b)

2024-03-28 18:11 UTC, iskanred requested changes
Там что-то с гитом случилось

Исправь, пожалуйста, затем проверю)

2024-03-28 18:11 UTC, iskanred commented on README.md
> +ФИО: ...
кажется, что-то пошло не так

2024-03-28 18:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/CommandConfig.java
> +        new UntrackCommand()
да, определенно что-то с гитом, иначе не понимаю, зачем возвращать старую реалиацию команд)

2024-03-28 18:24 UTC, iskanred requested changes
В общем пробежался быстренько. Заметил, что в этом PR пока не устранено разделение сервисов на реализации репозиториев. + про нейминг то, что в телеге обсудили, тут еще осталось.

Два небольших коммента + сломавшийся из-за гита PR.

Т.к. тесты на jooq добавил - принимаю домашку с 15/15 💯

Но в общем-то хотелось бы увидеть итоговую реализацию по всей 5й домашке в этом PR (или хотя бы в следующем), чтобы на PR 7й домашки уже смотреть с учетом всех предыдущих изменений)

Подскажи, пожалуйста, в каком PR внесешь итоговые правки и когда?

2024-03-28 18:24 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/LinkService.java
> +            throw new DuplicateLinkScrapperException("Ссылка уже существует", url + "уже отсвеживается");
`отсвеживается` очепятка)

2024-03-28 18:24 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/linkAdder/StackoverflowLinkAdder.java
> +        return jooqLinksRepository.addQuestion(
не к репозиториям применить сегрегацию интерфейсов (I из SOLID)? Выглядит не очень понятно, почему в linksRepository мы вызываем добавление вопроса?

2024-03-30 23:27 UTC, Fics3 commented
> Подскажи, пожалуйста, в каком PR внесешь итоговые правки и когда?

Полное разделение теперь в 7 домашке есть, замержил туда эту ветку

2024-04-04 19:22 UTC, iskanred approved these changes
✅

2024-04-05 21:52 UTC, merged