Hw6
Fics3/Tink_Java_Backend_Course_Spring pull request #7
Opened 2024-03-23 13:13 UTC by Fics3

2024-04-15 12:01 UTC, iskanred requested changes
🔥 Попытался "погонять" по JPA, однако придраться особо не к чему! Мне понравилось, лаконично, грамотно. Идеи можно реализовать по-разному, твоя реализация хороша!

💯 8/8 за дз, минорные правки отрпавил на исправления)

2024-04-15 12:01 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    AccessType databaseAccessType
чето класс становится god object, мб вынести все проперти из-под app? везде тащить application config тоже не очень понятно уже

2024-04-15 12:01 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/repository/jpa/JpaLinksRepository.java
> +            .orElseThrow(() -> new BadRequestScrapperException(USER_NOT_REGISTERED, ERROR));
точно ли bad request, а не 404 not found?

2024-04-15 12:01 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/repository/jpa/entity/ChatEntity.java
> +    }
зачем явно прописал?)

2024-04-15 12:01 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/repository/jpa/entity/ChatEntity.java
> +    }
если хочешь, можешь юзать noArgConstructor анноташку

2024-04-15 12:01 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/updateChecker/StackoverflowUpdateChecker.java
> +    private LinkUpdateRequest formLinkUpdateRequest(UUID linkId, URI url, String description) {
form - не очень используемый глагол, обычно либо create либо build

2024-04-15 12:01 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/repository/jpa/JpaLinksEntityRepositoryTest.java
> +    @Rollback
rollback для тестов вшита в transactional

если хочется, можешт аннотацию на уровень класса повесить, так же как и transactional

2024-04-17 17:52 UTC, Fics3 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    AccessType databaseAccessType
вынеc в clientConfig иницииализицию клиентов, а шедулер и аксес оставил в applicationConfig

2024-04-17 17:54 UTC, Fics3 commented on scrapper/src/main/java/edu/java/domain/repository/jpa/entity/ChatEntity.java
> +    }
Idea автоматически поставила, изменил на анноташку везде

2024-04-18 21:32 UTC, iskanred requested changes
минорные замечания и вопросики

2024-04-18 21:32 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/WebClientConfig.java
> +}
а для чего такая конфигурация?

2024-04-18 21:32 UTC, iskanred commented on scrapper/src/main/java/edu/java/ScrapperApplication.java
> +@EnableConfigurationProperties({ApplicationConfig.class, ClientConfig.class})
я бы указал пакет, потом мб еще появятся проперти классы

2024-04-20 23:53 UTC, Fics3 commented on scrapper/src/main/java/edu/java/configuration/WebClientConfig.java
> +}
случайно закоммитил, думал над архитектурой и не удалил, уже убрано

2024-04-21 00:01 UTC, Fics3 commented on scrapper/src/main/java/edu/java/ScrapperApplication.java
> +@EnableConfigurationProperties({ApplicationConfig.class, ClientConfig.class})
Надеюсь правильно понял и перед ними просто указал пакеты
это, как я понимаю, нужно, чтобы при наличии одинаковых названий, мы не искали в зависимостях, что где и как, а по путям в самих названиях

2024-04-21 23:02 UTC, iskanred requested changes
Одна правка с анноташкой

2024-04-21 23:02 UTC, iskanred commented on scrapper/src/main/java/edu/java/ScrapperApplication.java
> +@EnableConfigurationProperties({
кстати говоря, имел в виду не это)

Но это я недостаточно информации дал. В общем есть такая анноташка, как `@ConfigurationPropertiesScan`, которая уже включает в себя `@EnableConfigurationProperties`. Так вот в этой аннотации можно просто указать список пакетов для поиска или список классов, пакеты которых будут использованы для поиска. Т.е. в этом случае можно просто указать один из классов пропертей или название пакета и не нужно каждый раз указывать здесь новый проперти-класс при его добавлении.

https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/context/properties/ConfigurationPropertiesScan.html

https://www.baeldung.com/configuration-properties-in-spring-boot#1-spring-boot-22

2024-04-23 16:08 UTC, iskanred approved these changes
✅

2024-04-25 16:52 UTC, merged