Hw8
Fics3/Tink_Java_Backend_Course_Spring pull request #9
Opened 2024-04-05 22:01 UTC by Fics3

2024-04-25 18:50 UTC, iskanred requested changes
Все лаконично, здорово! 🔥

Единственное сейчас не соблюдается условие по отправки невалидных сообщений в очередь бота + тестов на все это дело с отправкой в dlq не хватило

Ну и тестов на кафка продюсер в scrapper и bot надо бы тоже завезти)

Поэтому на портале ставлю 6/6, чтобы успеть макс. балл набрать до дедлайна по стажировкам, но по факту 5/6 и отправлю на доработку в гитхабе

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfig.java
> +@Log4j2
`@EnableKafka` аннотация не понадобилась?

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfig.java
> +    public NewTopic topic() {
может, стоит назвать, какой топик, как у `dlqTopic`)

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfig.java
> +        return new DefaultKafkaProducerFactory<>(configProps());
у тебя почему-то producer factory properties в отдельном бине, а consumer factory properties прям в том же методе, надо бы однообразно сделать

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfig.java
> +        return new DefaultKafkaProducerFactory<>(configProps());
\+ когда бином делаешь, лучше этот бин в метод инжектить, а не вызывать метод:
 ```java
 @Bean
public ProducerFactory<String, LinkUpdateRequest> producerFactory(Map<String, Object> configProps) {
    return new DefaultKafkaProducerFactory<>(configProps);
}
```

иначе метод configProps два раза дергается: при создании самого бина configProps и при создании producer factory бина

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfig.java
> +public class KafkaConfig {
Я бы конфигурацию поделил на две: для продюсера и для консьюмера, так чиать попроще было бы

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/KafkaNotificationProcessorService.java
> +    public void listen(LinkUpdateRequest linkUpdateRequest) {
а ты тестил с невалидными сообщениями?

смотри, если сообщение невалидное (нет какого-то поля, или по-другому называется, или вообще пустой json), то кафка ошибку кинет не на уровне метода, а за его пределами, попытаясь распарсить сообщение в объект типа LinkUpdateResponse

надо сделать либо кастомный обработчик ошибок и положит в аннотацию @KafkaListener:
https://docs.spring.io/spring-kafka/reference/kafka/annotation-error-handling.html

либо чуть попроще распарсить сообщение в строку (@Payload), а дальше уже пытаться его валидировать / парсить и контролировать ошибки самому:
https://docs.spring.io/spring-kafka/reference/kafka/receiving-messages/validation.html
https://stackoverflow.com/questions/46325540/how-to-use-spring-kafkas-acknowledgement-acknowledge-method-for-manual-commit

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/KafkaNotificationProcessorService.java
> +            log.info("Битое сообщение -> DLQ: ");
двоеточие, пробел ииии)

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfig.java
> +        return TopicBuilder.name(applicationConfig.kafkaProperties().topic().name())
а зачем тебе вообще эти бины `NewTopic`? Вроде не используется нигде

2024-04-25 18:50 UTC, iskanred commented on bot/src/main/resources/application.yaml
> +      replicas-num: 1
не очень понимаю, зачем информация клиентскому приложению

мб даже и нужна как-то, но вроде в задании нет и у тебя в сервисе никак не используется

2024-04-25 18:50 UTC, iskanred commented on compose.yml
> +      - ./scrapper/src/main/resources/docker/kafka_jaas_config.conf:/etc/kafka/kafka_config_jaas.conf
в задании просили именнованый volume
![image](https://github.com/Fics3/tink_java_backend_course_spring/assets/37081728/0c3c497f-e22d-4367-8cdf-d3f8f65191e3)

https://stackoverflow.com/questions/35841241/docker-compose-named-mounted-volume

2024-04-25 18:50 UTC, iskanred commented on compose.yml
> +  schema-registry:
за схему-реджистри респект!

2024-04-25 18:50 UTC, iskanred commented on compose.yml
> +    depends_on:
кафка и зукуипер могут стартовать, но еще не быть готовыми к приему-передаче, поэтому рекомендую изучать readiness пробы в docker-compose, а именно condition'ы и healthcheck'и 

https://docs.docker.com/compose/startup-order/
https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y

2024-04-25 18:50 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/NotificationService.java
> +        if (applicationConfig.isUseQueue()) {
это, кстати, интересное решение

оно круто, если ты хочешь переключать флаг в рантайме (и система так устроена, что она позволяет это делать), тогда новые вызовы `sendNotification` пойдут по флоу вызова другого сервиса

Но базово, когда такой флоу не предусматривается и изменение флага должно аффектить только при перезапуске, я бы рекомендовал навешивать `@Conditional...` аннотации на соответсвтующие сервисы и реализовать один интерфейс:

```java
interface BotUpdateSender { void sendUpdate() }

@ConditionalOnHavingValue("useQueue=true")
class KafkaBotUpdateSender { ... }

@ConditionalOnMissinBean(KafkaBotUpdateSender.class)
class RestBotUpdateSender { ... }

class NotificationService {
    private final BotUpdateSender botUpdateSender;
}
```

2024-04-26 10:43 UTC, Fics3 commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfig.java
> +@Log4j2
Вот такую штуку нашел
https://stackoverflow.com/questions/61256925/in-spring-kafka-do-i-need-to-add-the-enablekafka-annotation-to-my-application

2024-04-29 23:16 UTC, Fics3 commented
сколько боли в этих тестах кафки

2024-04-30 20:04 UTC, iskanred approved these changes
✅

2024-04-30 20:49 UTC, merged